apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
  name: socket-ns
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cntmap
  namespace: socket-ns
data:
  cntname: "ABC"
  cntip: "192.168.2.40"
  cntport: "30014"
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: microk8s-hostpath
  namespace: socket-ns
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: microk8s.io/hostpath
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: ar-pv
  namespace: socket-ns
  labels:
    app: ar
    type: local
spec:
  storageClassName: microk8s-hostpath
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/data-ar"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ar-pv-claim
  namespace: socket-ns
  labels:
    app: ar
spec:
  storageClassName: microk8s-hostpath
  capacity:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi