kind: PersistentVolume
apiVersion: v1
metadata:
  name: cnt-pv
  namespace: socket-ns
  labels:
    app: cnt
    type: local
spec:
  storageClassName: microk8s-hostpath
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/data-ar"
#---
#kind: PersistentVolumeClaim
#apiVersion: v1
#metadata:
#  name: cnt-pv-claim
#  namespace: socket-ns
#  labels:
#    app: cnt
#spec:
#  storageClassName: microk8s-hostpath
#  capacity:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 5Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cnt-statefulset
  namespace: socket-ns
  labels:
    app: cnt
spec:
  serviceName: "cnt"
  replicas: 1
  selector:
    matchLabels:
      app: cnt
  template:
    metadata:
      labels:
        app: cnt
    spec:
      containers:
      - name: cnt-pod
        image: localhost:32000/i_cnt:v1.0.1
        ports:
        - containerPort: 2001
          name: tcp-cnt
        volumeMounts:
        - name: cnt-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: cnt-data
        persistentVolumeClaim:
          claimName: ar-pv-claim
#          claimName: cnt-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: cnt-service
  namespace: socket-ns
  labels:
    app: cnt
spec:
  ports:
  - port: 2001
    protocol: TCP
    name: tcp-cnt-name
    nodePort: 30014
    targetPort: tcp-cnt
  type: NodePort 
  selector:
    app: cnt
