apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: socket1
  name: socket1-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: s1
  revisionHistoryLimit: 3
  progressDeadlineSeconds: 300
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: s1
    spec:
      containers:
      - name: s1-pod
        image: localhost:32000/i_socket:v1.0.4
        ports:
        - containerPort: 2011
          name: s1-http
